import os
import django
import random

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from curriculum.models import Level, Course, Discipline
from questions.models import Question, QuestionOption
from django.contrib.auth import get_user_model

# Clean data first to avoid unique constraint errors if re-ran
print("Cleaning database...")
Level.objects.all().delete()
Question.objects.all().delete()
User = get_user_model()

print("Creating dummy data...")

levels_data = ['Level 100', 'Level 200', 'Level 300', 'Level 400', 'Level 500', 'Level 600']
courses_data = ['Anatomy', 'Physiology', 'Biochemistry', 'Pathology', 'Pharmacology', 'Surgery', 'Internal Medicine', 'Pediatrics']
disciplines_data = {
    'Anatomy': ['Upper Limb', 'Lower Limb', 'Thorax', 'Abdomen', 'Pelvis', 'Neuroanatomy'],
    'Physiology': ['CVS Physiology', 'Respiratory', 'Renal', 'GI', 'Endocrine'],
    'Biochemistry': ['Metabolism', 'Genetics', 'Enzymology', 'Nutrition'],
    'Pathology': ['General Pathology', 'Systemic Pathology', 'Hematology', 'Microbiology'],
    'Pharmacology': ['General Pharma', 'Autonomic Nervous System', 'CNS', 'CVS Drugs', 'Chemotherapy'],
    'Surgery': ['General Surgery', 'Orthopedics', 'Urology', 'Neurosurgery'],
    'Internal Medicine': ['Cardiology', 'Pulmonology', 'Gastroenterology', 'Neurology', 'Endocrinology'],
    'Pediatrics': ['Neonatology', 'Infectious Diseases', 'Nutrition', 'Genetics']
}

difficulty_choices = ['easy', 'medium', 'hard']

courses_created = 0
disciplines_created = 0
questions_created = 0

for level_name in levels_data:
    level = Level.objects.create(name=level_name, order=int(level_name.split(' ')[1]))
    
    # Pick 3 random courses for this level to avoid too much clustering
    level_courses = random.sample(courses_data, k=3)
    for course_name in level_courses:
        course = Course.objects.create(level=level, name=course_name, code=f"{course_name[:3].upper()}{level.order}")
        courses_created += 1
        
        # Pick 2-4 disciplines per course
        course_disciplines = disciplines_data.get(course_name, ['General'])
        selected_disciplines = random.sample(course_disciplines, k=min(len(course_disciplines), random.randint(2, 4)))
        
        for disc_name in selected_disciplines:
            discipline = Discipline.objects.create(course=course, name=disc_name)
            disciplines_created += 1
            
            # Create exactly 12 questions per discipline
            for i in range(12):
                q = Question(
                    level=level,
                    course=course,
                    discipline=discipline,
                    text=f"Dummy Question {i+1} concerning {disc_name} in {course_name} ({level_name}). What is the clinical significance?",
                    explanation=f"This is an autogenerated explanation detailing the clinical significance of {disc_name}.",
                    question_type='SBA',
                    difficulty=random.choice(difficulty_choices),
                    status='published',
                    source_year=random.choice([2020, 2021, 2022, 2023, None])
                )
                q.save() # need to save to get ID for options and to trigger full_clean
                questions_created += 1
                
                # Options
                options = ["Option A", "Option B", "Option C", "Option D", "Option E"]
                random.shuffle(options)
                correct_index = random.randint(0, 4)
                
                for idx, opt_text in enumerate(options):
                    QuestionOption.objects.create(
                        question=q,
                        text=f"{opt_text} for {disc_name} question {i+1}",
                        is_correct=(idx == correct_index),
                        order=idx
                    )

print(f"Seeding Complete!")
print(f"Created {len(levels_data)} levels, {courses_created} courses, {disciplines_created} disciplines, and {questions_created} questions.")
